# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd63f70994af80ef79b6bb1d3ef861806cbbfedc318fb217acb5e949c4561189816183a43d5b7e41417e32f5bf1aeb015d751362a695cef96396a880f4590f53
  user: admin
  password: IOTAS1000
test:
  secret_key_base: e0d21045aa1adba090c32c729ed659f61e74f6029a6bff50a1e8d58501fb074230d9dde8df534a8aed4d815a3de8e74d3501b14c8ffbc3a83e85066c40f1cea0
  user: admin
  password: IOTAS1000
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  user: admin
  password: IOTAS1000
  gmail_user: berkeleyliveglass@gmail.com
  gmail_pass: IOTAS1000
  stripe_public_test: pk_test_quzeHkGlWTdTO0rjS0MdY0LS
  stripe_private_test: sk_test_gEaFjlOfJvnGtpMxejGSf2rw
  stripe_public: pk_live_uBlbxIhCQ4FTFVzl9lAwLhz9
  stripe_private: sk_live_Oq4qMOlOgnUyjniIGa0Xa1Ub